import axiosClient from "@/libs/axios/axios-client";
import type {
  GetContractProps,
  GetContractResult,
} from "@/types/website/contract";

async function getContractById({ id }: GetContractProps): GetContractResult {
  // return {
  //   contract_file: null,
  //   editcontract_file: null,
  //   mls: 12,
  //   sellers: [
  //     {
  //       id: "seller-1757860740598",
  //       seller_name: "string",
  //       seller_mothor_name: "string",
  //       seller_birth_place: "string",
  //       seller_nation_number: 234324,
  //       seller_registry: "string",
  //     },
  //   ],
  //   buyers: [
  //     {
  //       buyer_name: null,
  //       buyer_mothor_name: null,
  //       buyer_birth_place: null,
  //       buyer_nation_number: null,
  //       buyer_registry: null,
  //     },
  //   ],
  //   seller_name: "string",
  //   seller_mothor_name: "string",
  //   seller_birth_place: "string",
  //   seller_nation_number: 234324,
  //   seller_registry: "string",
  //   buyer_name: null,
  //   buyer_mothor_name: null,
  //   buyer_birth_place: null,
  //   buyer_nation_number: null,
  //   buyer_registry: null,
  //   building_num: "D080093",
  //   street: "كعب بن زهير",
  //   floor: 3,
  //   apt: 1,
  //   country: "Homs",
  //   city: "Homs",
  //   area: "الإنشاءات ",
  //   legal_description: "985123",
  //   balconies: 2,
  //   fan_number: null,
  //   water: "main",
  //   elevator: false,
  //   ac: true,
  //   garage: false,
  //   garden: false,
  //   jacuzzi: false,
  //   solar_system: true,
  //   pool: false,
  //   price: null,
  //   deposit: null,
  //   deposit_date: null,
  //   batch: null,
  //   batch_date: null,
  //   final_price: null,
  //   warranty_agent: null,
  //   warranty_agent_address: null,
  //   warranty_agent_phone: null,
  //   warranty_agent_email: null,
  //   warranty_agent_fax: null,
  //   addtion_batch_days: null,
  //   addtion_batch_date: null,
  //   days: null,
  //   days_batch: null,
  //   financing: null,
  //   others: null,
  //   balance: null,
  //   effective_date: null,
  //   agent_signature: null,
  //   sller_agent_name: "humam safi",
  //   seller_agent_license: null,
  //   seller_agent_broker: null,
  //   seller_agent_broker_license: null,
  //   seller_company_address: "",
  //   seller_company_phone: 912345678,
  //   seller_commission: 1,
  //   buyer_agent: null,
  //   buyer_agent_license: null,
  //   buyer_agent_broker: null,
  //   buyer_agent_broker_license: null,
  //   buyer_company_address: null,
  //   buyer_company_phone: null,
  //   buyer_commission: 1,
  // };
  const res = await axiosClient.get(`contracts/${id}`);

  console.log({ res });
  return res?.data;
}

export default getContractById;
